# Generated by Django 3.1 on 2021-11-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='results',
            field=models.ManyToManyField(blank=True, to='app.Results'),
        ),
    ]
