# Generated by Django 3.1 on 2021-11-11 18:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211111_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keys',
            name='results',
        ),
        migrations.AddField(
            model_name='keys',
            name='counter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='results',
            name='key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.keys'),
            preserve_default=False,
        ),
    ]
