# Generated by Django 3.1 on 2021-11-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathology', models.CharField(max_length=50, verbose_name='pathology')),
                ('image', models.ImageField(upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Heatmap',
                'verbose_name_plural': 'Heatmaps',
            },
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
