# Generated by Django 3.1 on 2021-12-01 00:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_results_heatmaps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='heatmaps',
        ),
        migrations.AddField(
            model_name='results',
            name='heatmaps_links',
            field=models.CharField(blank=True, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Heatmap',
        ),
    ]
