# Generated by Django 3.1 on 2021-12-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211130_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatmapLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'HeatmapLink',
                'verbose_name_plural': 'HeatmapLinks',
            },
        ),
        migrations.RemoveField(
            model_name='results',
            name='heatmaps_links',
        ),
        migrations.AddField(
            model_name='results',
            name='heatmaps_links',
            field=models.ManyToManyField(to='app.HeatmapLink'),
        ),
    ]
