# Generated by Django 3.1 on 2021-12-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211130_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatmaplink',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
