# Generated by Django 3.1 on 2021-12-01 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_heatmaplink_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatmaplink',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.results'),
        ),
    ]
